//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCourse()
        {
            this.tblResult = new HashSet<tblResult>();
        }
    
        public int idCourse { get; set; }
        public Nullable<int> intEvent { get; set; }
        public string strName { get; set; }
        public Nullable<short> intLength { get; set; }
        public Nullable<short> intClimb { get; set; }
        public Nullable<short> intControls { get; set; }
        public Nullable<int> intTechnical { get; set; }
        public Nullable<int> intLog { get; set; }
        public string strSplitsURL { get; set; }
        public short intListOrder { get; set; }
    
        public virtual lutTechnical lutTechnical { get; set; }
        public virtual tblEvent tblEvent { get; set; }
        public virtual tblLog tblLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResult> tblResult { get; set; }
    }
}
