//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDownload
    {
        public int idDownload { get; set; }
        public string strTitle { get; set; }
        public string strDescription { get; set; }
        public int intFile { get; set; }
    }
}
