//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvent()
        {
            this.tblCourse = new HashSet<tblCourse>();
        }
    
        public int idEvent { get; set; }
        public string strName { get; set; }
        public Nullable<System.DateTime> dteDate { get; set; }
        public Nullable<int> intVenue { get; set; }
        public string strContact { get; set; }
        public Nullable<int> intPlanner { get; set; }
        public Nullable<int> intController { get; set; }
        public string strResults { get; set; }
        public string strPhotos { get; set; }
        public string strPlannerReport { get; set; }
        public string strControllerReport { get; set; }
        public string strSpecialNote { get; set; }
        public string strRegTime { get; set; }
        public string strStarts { get; set; }
        public string strClose { get; set; }
        public string strDirections { get; set; }
        public string strCourses { get; set; }
        public string strNotice { get; set; }
        public Nullable<int> intMaxPoints { get; set; }
        public Nullable<int> intOrganisingClub { get; set; }
        public string strCost1 { get; set; }
        public Nullable<decimal> decCoordinateLat { get; set; }
        public Nullable<decimal> decCoordinateLong { get; set; }
        public string strCost { get; set; }
    
        public virtual lutClub lutClub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCourse> tblCourse { get; set; }
        public virtual tblVenue tblVenue { get; set; }
        public virtual tblCompetitor tblCompetitor_Controller { get; set; }
        public virtual tblCompetitor tblCompetitor_Planner { get; set; }
    }
}
