//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMembership
    {
        public int idMembership { get; set; }
        public Nullable<int> intClub { get; set; }
        public Nullable<int> intYear { get; set; }
    
        public virtual lutClub lutClub { get; set; }
    }
}
