//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNews
    {
        public int idNews { get; set; }
        public string strNews { get; set; }
        public System.DateTime dteDate { get; set; }
        public string strTitle { get; set; }
    }
}
