//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblResult()
        {
            this.tblSplit = new HashSet<tblSplit>();
        }
    
        public int intCompetitor { get; set; }
        public int intCourse { get; set; }
        public Nullable<int> intClub { get; set; }
        public Nullable<int> intCategory { get; set; }
        public Nullable<System.DateTime> dteTime { get; set; }
        public bool blnDisqualified { get; set; }
        public string strComment { get; set; }
        public Nullable<int> intPosition { get; set; }
        public Nullable<int> intPoints { get; set; }
        public string strRaceNumber { get; set; }
    
        public virtual tblCompetitor tblCompetitor { get; set; }
        public virtual tblCourse tblCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSplit> tblSplit { get; set; }
    }
}
