//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSplit
    {
        public int intCompetitor { get; set; }
        public int intCourse { get; set; }
        public int intSplitNumber { get; set; }
        public string strSplitName { get; set; }
        public Nullable<System.DateTime> dteSplitTime { get; set; }
        public Nullable<System.DateTime> dteCumTime { get; set; }
    
        public virtual tblResult tblResult { get; set; }
    }
}
